server:
  port: 8082

servlet:
  context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  #热部署--配置文件
  devtools:
    restart:
     enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  application:
      name: provider-client
      #注册的客户端名字


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.providerpayment8001.pojo
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: false


eureka:
  client:
    service-url:
      register-with-eureka: true
      #表示不向注册中心注册自己
      fetch-registry: true
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
#lOG
logging:
  level:
    com.example: DEBUG