server:
  port: 8081

spring:
  application:
    name: zookeeper-provider
  cloud:
    zookeeper:
      connect-string: 192.168.126.129:2181
  #zookeperip+端口号
  #热部署--配置文件
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
    #注册的客户端名字


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: false
